<?php
/*
 * CreatUser:Make Money
 * Date: 2021-07-13 23:17
 */
namespace app\common\controller;
use think\Controller;

/**
 * Class BackController
 * @package app\common\controller
 * 后台控制基类
 */
class BackController extends Controller
{

    protected function _initialize()
    {
        echo '继承基类';
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}